### ISSUE TITLE
Deno implementation

### ISSUE THREAD

**Issue by bolte-io** [Shubham-Kumar-2000/protocol-registry#20]
Hey, can you give me some tips on converting this for use with Deno? Is this planned for the future?

**Comment by Shubham-Kumar-2000** [comment]
No, It is not planned yet because most of our dependencies doesn't support it.

For now you can use the [cli ](https://www.npmjs.com/package/protocol-registry-cli)version of this package and run it as a child process.
https://www.npmjs.com/package/protocol-registry-cli

Closing this issue for now. Will re-open when we will plan about deno.
